

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root@123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka (common for all services)
eureka.client.service-url.defaultZone=http://localhost:8763/eureka
eureka.instance.prefer-ip-address=true


# Logging (optional)
logging.level.org.springframework.web=INFO
